package handlers

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"net"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"

	"growth-lms/internal/httpserver/middleware"
	"growth-lms/internal/models"
)

// SetCustomDomain is POST /api/orgs/:org_slug/domain, owner-only. It
// records the candidate domain and generates a fresh verification token
// the org owner must publish as a DNS TXT record before VerifyDomain will
// succeed — see that handler's doc comment for why this can't be trusted
// from the browser alone.
func SetCustomDomain(d *AuthDeps) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req struct {
			Domain string `json:"domain" binding:"required"`
		}
		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request"})
			return
		}
		domain := strings.ToLower(strings.TrimSpace(req.Domain))
		if domain == "" || strings.ContainsAny(domain, " /") {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid domain"})
			return
		}

		tokenBytes := make([]byte, 16)
		if _, err := rand.Read(tokenBytes); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "internal error"})
			return
		}
		token := hex.EncodeToString(tokenBytes)

		ctx := c.Request.Context()
		tx, _ := middleware.RequestTxFromGin(c)
		ac, _ := middleware.AuthContextFromGin(c)
		oc, _ := middleware.OrgContextFromGin(c)

		if err := d.Orgs.SetCustomDomain(ctx, tx, oc.OrgID, domain, token); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "internal error"})
			return
		}
		_ = d.Audit.Record(ctx, tx, models.AuditEvent{
			OrgID: &oc.OrgID, UserID: &ac.UserID, Action: "org.domain_set", ResourceType: "organization", ResourceID: &oc.OrgID,
			IPAddress: c.ClientIP(), UserAgent: c.Request.UserAgent(),
		})

		c.JSON(http.StatusOK, gin.H{
			"domain":                 domain,
			"verification_txt_name":  fmt.Sprintf("_growthlms-verify.%s", domain),
			"verification_txt_value": token,
		})
	}
}

// VerifyDomain is POST /api/orgs/:org_slug/domain/verify, owner-only. It
// performs a real DNS TXT lookup against _growthlms-verify.<domain> and
// only marks the domain verified if the record's value matches the token
// generated by SetCustomDomain — a domain can't be "verified" just
// because the owner claims to control it; they must prove DNS control.
func VerifyDomain(d *AuthDeps) gin.HandlerFunc {
	return func(c *gin.Context) {
		ctx := c.Request.Context()
		tx, _ := middleware.RequestTxFromGin(c)
		ac, _ := middleware.AuthContextFromGin(c)
		oc, _ := middleware.OrgContextFromGin(c)

		b, err := d.Orgs.GetBranding(ctx, tx, oc.Slug)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "internal error"})
			return
		}
		if b.CustomDomain == nil || b.DomainVerificationToken == nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "no domain pending verification"})
			return
		}

		recordName := fmt.Sprintf("_growthlms-verify.%s", *b.CustomDomain)
		records, err := net.LookupTXT(recordName)
		if err != nil {
			c.JSON(http.StatusOK, gin.H{"verified": false, "error": "TXT record not found"})
			return
		}

		verified := false
		for _, rec := range records {
			if rec == *b.DomainVerificationToken {
				verified = true
				break
			}
		}
		if !verified {
			c.JSON(http.StatusOK, gin.H{"verified": false, "error": "TXT record does not match"})
			return
		}

		if err := d.Orgs.MarkDomainVerified(ctx, tx, oc.OrgID); err != nil {
			if errors.Is(err, models.ErrNotFound) {
				c.JSON(http.StatusNotFound, gin.H{"error": "organization not found"})
				return
			}
			c.JSON(http.StatusInternalServerError, gin.H{"error": "internal error"})
			return
		}
		_ = d.Audit.Record(ctx, tx, models.AuditEvent{
			OrgID: &oc.OrgID, UserID: &ac.UserID, Action: "org.domain_verified", ResourceType: "organization", ResourceID: &oc.OrgID,
			IPAddress: c.ClientIP(), UserAgent: c.Request.UserAgent(),
		})
		c.JSON(http.StatusOK, gin.H{"verified": true})
	}
}
