run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - gosimple
    - bodyclose
    - gosec
    - misspell
    - unconvert

issues:
  exclude-dirs:
    - tmp
